

services:
  backend:
    container_name: facecrime_backend
    network_mode: "host"          # your FastAPI binds to 0.0.0.0:8443
    build:
      context: .
      dockerfile: Dockerfile
    restart: always


    gpus: all





    environment:
      - HARRISON_DB_DB=${HARRISON_DB_DB}
      - HARRISON_DB_USER=${HARRISON_DB_USER}
      - HARRISON_DB_PASSWORD=${HARRISON_DB_PASSWORD}
      - HARRISON_DB_HOST=${HARRISON_DB_HOST}
      - HARRISON_DB_PORT=${HARRISON_DB_PORT}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

    # no ports: under host mode your service is already on :8443

